//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gym
    {
        public int GymID { get; set; }
        public string GymName { get; set; }
        public string GymManager { get; set; }
        public string GymAddress { get; set; }
        public string GymTel { get; set; }
        public string GymWebsite { get; set; }
        public string GymInstagram { get; set; }
        public string GymTelegram { get; set; }
        public string GymWhatsup { get; set; }
        public string GymWork { get; set; }
        public string Gymsmsusername { get; set; }
        public string GymsmsPass { get; set; }
        public string Gymsmssender { get; set; }
        public string Gymreciew { get; set; }
        public string GymWeekend { get; set; }
        public byte[] GymLogo { get; set; }
        public System.Guid PicID { get; set; }
    }
}
