//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Gym_DBEntities : DbContext
    {
        public Gym_DBEntities()
            : base("name=Gym_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gym> Gym { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<NewProgram> NewProgram { get; set; }
        public virtual DbSet<NewProgramItem> NewProgramItem { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<People> People { get; set; }
        public virtual DbSet<Period> Period { get; set; }
        public virtual DbSet<PeriodItems> PeriodItems { get; set; }
        public virtual DbSet<Program> Program { get; set; }
        public virtual DbSet<Shahrieh> Shahrieh { get; set; }
        public virtual DbSet<vw_log> vw_log { get; set; }
        public virtual DbSet<vw_newprogram> vw_newprogram { get; set; }
        public virtual DbSet<Vw_Period> Vw_Period { get; set; }
        public virtual DbSet<vw_Peyment> vw_Peyment { get; set; }
        public virtual DbSet<Vw_Program> Vw_Program { get; set; }
        public virtual DbSet<vw_shahrieh> vw_shahrieh { get; set; }
    
        public virtual int ClosePeriod(Nullable<int> id, string desc)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var descParameter = desc != null ?
                new ObjectParameter("desc", desc) :
                new ObjectParameter("desc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ClosePeriod", idParameter, descParameter);
        }
    
        public virtual int closetheprogram(Nullable<int> id, string desc)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var descParameter = desc != null ?
                new ObjectParameter("desc", desc) :
                new ObjectParameter("desc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("closetheprogram", idParameter, descParameter);
        }
    
        public virtual int deletePeople(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deletePeople", idParameter);
        }
    
        public virtual int ExitPersonDate(Nullable<int> id, string date)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var dateParameter = date != null ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ExitPersonDate", idParameter, dateParameter);
        }
    
        public virtual ObjectResult<findProgramID_Result> findProgramID()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<findProgramID_Result>("findProgramID");
        }
    
        public virtual int GetSmsValue(ObjectParameter username, ObjectParameter password, ObjectParameter sender)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetSmsValue", username, password, sender);
        }
    
        public virtual int InsertGym1(string name, string manager, string address, string tel, string website, string insta, string telegram, string whatsup, string workhour, string smsusername, string pass, string sender, string weekend, byte[] logo)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var managerParameter = manager != null ?
                new ObjectParameter("manager", manager) :
                new ObjectParameter("manager", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var telParameter = tel != null ?
                new ObjectParameter("tel", tel) :
                new ObjectParameter("tel", typeof(string));
    
            var websiteParameter = website != null ?
                new ObjectParameter("website", website) :
                new ObjectParameter("website", typeof(string));
    
            var instaParameter = insta != null ?
                new ObjectParameter("insta", insta) :
                new ObjectParameter("insta", typeof(string));
    
            var telegramParameter = telegram != null ?
                new ObjectParameter("telegram", telegram) :
                new ObjectParameter("telegram", typeof(string));
    
            var whatsupParameter = whatsup != null ?
                new ObjectParameter("whatsup", whatsup) :
                new ObjectParameter("whatsup", typeof(string));
    
            var workhourParameter = workhour != null ?
                new ObjectParameter("workhour", workhour) :
                new ObjectParameter("workhour", typeof(string));
    
            var smsusernameParameter = smsusername != null ?
                new ObjectParameter("smsusername", smsusername) :
                new ObjectParameter("smsusername", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            var senderParameter = sender != null ?
                new ObjectParameter("sender", sender) :
                new ObjectParameter("sender", typeof(string));
    
            var weekendParameter = weekend != null ?
                new ObjectParameter("weekend", weekend) :
                new ObjectParameter("weekend", typeof(string));
    
            var logoParameter = logo != null ?
                new ObjectParameter("logo", logo) :
                new ObjectParameter("logo", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertGym1", nameParameter, managerParameter, addressParameter, telParameter, websiteParameter, instaParameter, telegramParameter, whatsupParameter, workhourParameter, smsusernameParameter, passParameter, senderParameter, weekendParameter, logoParameter);
        }
    
        public virtual int InsertGym2(string name, string manager, string address, string tel, string website, string insta, string telegram, string whatsup, string workhour, string smsusername, string pass, string sender, string weekend)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var managerParameter = manager != null ?
                new ObjectParameter("manager", manager) :
                new ObjectParameter("manager", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var telParameter = tel != null ?
                new ObjectParameter("tel", tel) :
                new ObjectParameter("tel", typeof(string));
    
            var websiteParameter = website != null ?
                new ObjectParameter("website", website) :
                new ObjectParameter("website", typeof(string));
    
            var instaParameter = insta != null ?
                new ObjectParameter("insta", insta) :
                new ObjectParameter("insta", typeof(string));
    
            var telegramParameter = telegram != null ?
                new ObjectParameter("telegram", telegram) :
                new ObjectParameter("telegram", typeof(string));
    
            var whatsupParameter = whatsup != null ?
                new ObjectParameter("whatsup", whatsup) :
                new ObjectParameter("whatsup", typeof(string));
    
            var workhourParameter = workhour != null ?
                new ObjectParameter("workhour", workhour) :
                new ObjectParameter("workhour", typeof(string));
    
            var smsusernameParameter = smsusername != null ?
                new ObjectParameter("smsusername", smsusername) :
                new ObjectParameter("smsusername", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            var senderParameter = sender != null ?
                new ObjectParameter("sender", sender) :
                new ObjectParameter("sender", typeof(string));
    
            var weekendParameter = weekend != null ?
                new ObjectParameter("weekend", weekend) :
                new ObjectParameter("weekend", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertGym2", nameParameter, managerParameter, addressParameter, telParameter, websiteParameter, instaParameter, telegramParameter, whatsupParameter, workhourParameter, smsusernameParameter, passParameter, senderParameter, weekendParameter);
        }
    
        public virtual int InsertLogin(string username, string password, string name)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertLogin", usernameParameter, passwordParameter, nameParameter);
        }
    
        public virtual int InsertPay(Nullable<int> id, Nullable<int> pay, string date, string status, string save)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var payParameter = pay.HasValue ?
                new ObjectParameter("Pay", pay) :
                new ObjectParameter("Pay", typeof(int));
    
            var dateParameter = date != null ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(string));
    
            var statusParameter = status != null ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(string));
    
            var saveParameter = save != null ?
                new ObjectParameter("save", save) :
                new ObjectParameter("save", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertPay", idParameter, payParameter, dateParameter, statusParameter, saveParameter);
        }
    
        public virtual int InsertPeople(string name, string mobile, string address, string mellicode, string type, string type2, Nullable<int> deptor, Nullable<int> creditor, byte[] logo)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("mobile", mobile) :
                new ObjectParameter("mobile", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var mellicodeParameter = mellicode != null ?
                new ObjectParameter("mellicode", mellicode) :
                new ObjectParameter("mellicode", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var type2Parameter = type2 != null ?
                new ObjectParameter("type2", type2) :
                new ObjectParameter("type2", typeof(string));
    
            var deptorParameter = deptor.HasValue ?
                new ObjectParameter("deptor", deptor) :
                new ObjectParameter("deptor", typeof(int));
    
            var creditorParameter = creditor.HasValue ?
                new ObjectParameter("creditor", creditor) :
                new ObjectParameter("creditor", typeof(int));
    
            var logoParameter = logo != null ?
                new ObjectParameter("logo", logo) :
                new ObjectParameter("logo", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertPeople", nameParameter, mobileParameter, addressParameter, mellicodeParameter, typeParameter, type2Parameter, deptorParameter, creditorParameter, logoParameter);
        }
    
        public virtual int InsertPeople2(string name, string mobile, string address, string mellicode, string type, string type2, Nullable<int> deptor, Nullable<int> creditor)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("mobile", mobile) :
                new ObjectParameter("mobile", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var mellicodeParameter = mellicode != null ?
                new ObjectParameter("mellicode", mellicode) :
                new ObjectParameter("mellicode", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var type2Parameter = type2 != null ?
                new ObjectParameter("type2", type2) :
                new ObjectParameter("type2", typeof(string));
    
            var deptorParameter = deptor.HasValue ?
                new ObjectParameter("deptor", deptor) :
                new ObjectParameter("deptor", typeof(int));
    
            var creditorParameter = creditor.HasValue ?
                new ObjectParameter("creditor", creditor) :
                new ObjectParameter("creditor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertPeople2", nameParameter, mobileParameter, addressParameter, mellicodeParameter, typeParameter, type2Parameter, deptorParameter, creditorParameter);
        }
    
        public virtual int InsertPeriod(Nullable<int> id, string date)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var dateParameter = date != null ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertPeriod", idParameter, dateParameter);
        }
    
        public virtual int InsertPeriodItem(Nullable<int> id, string product, string count, Nullable<int> fee)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var productParameter = product != null ?
                new ObjectParameter("Product", product) :
                new ObjectParameter("Product", typeof(string));
    
            var countParameter = count != null ?
                new ObjectParameter("count", count) :
                new ObjectParameter("count", typeof(string));
    
            var feeParameter = fee.HasValue ?
                new ObjectParameter("fee", fee) :
                new ObjectParameter("fee", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertPeriodItem", idParameter, productParameter, countParameter, feeParameter);
        }
    
        public virtual int InsertPersonDate(Nullable<int> id, string date)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var dateParameter = date != null ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertPersonDate", idParameter, dateParameter);
        }
    
        public virtual int insertProgram(Nullable<int> id, string item, string count)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var itemParameter = item != null ?
                new ObjectParameter("item", item) :
                new ObjectParameter("item", typeof(string));
    
            var countParameter = count != null ?
                new ObjectParameter("count", count) :
                new ObjectParameter("count", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertProgram", idParameter, itemParameter, countParameter);
        }
    
        public virtual int insertprogramnew(Nullable<int> id, string date)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var dateParameter = date != null ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertprogramnew", idParameter, dateParameter);
        }
    
        public virtual int insertshahriehdate(Nullable<int> id, string datein, string dateout)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var dateinParameter = datein != null ?
                new ObjectParameter("datein", datein) :
                new ObjectParameter("datein", typeof(string));
    
            var dateoutParameter = dateout != null ?
                new ObjectParameter("dateout", dateout) :
                new ObjectParameter("dateout", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insertshahriehdate", idParameter, dateinParameter, dateoutParameter);
        }
    
        public virtual ObjectResult<KartOzviat_Result> KartOzviat(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KartOzviat_Result>("KartOzviat", idParameter);
        }
    
        public virtual ObjectResult<lastLogOut_Result> lastLogOut(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<lastLogOut_Result>("lastLogOut", idParameter);
        }
    
        public virtual int SaveProgram(Nullable<int> id, string name, string title, byte[] binary)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var binaryParameter = binary != null ?
                new ObjectParameter("binary", binary) :
                new ObjectParameter("binary", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveProgram", idParameter, nameParameter, titleParameter, binaryParameter);
        }
    
        public virtual ObjectResult<ShowPeople_Result> ShowPeople()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ShowPeople_Result>("ShowPeople");
        }
    
        public virtual ObjectResult<ShowPeopleByID_Result> ShowPeopleByID(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ShowPeopleByID_Result>("ShowPeopleByID", idParameter);
        }
    
        public virtual ObjectResult<ShowPeriods_Result> ShowPeriods(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ShowPeriods_Result>("ShowPeriods", idParameter);
        }
    
        public virtual ObjectResult<ShowProgram_Result> ShowProgram(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ShowProgram_Result>("ShowProgram", idParameter);
        }
    
        public virtual int updatedeptor1(Nullable<int> id, Nullable<int> deptor)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var deptorParameter = deptor.HasValue ?
                new ObjectParameter("deptor", deptor) :
                new ObjectParameter("deptor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updatedeptor1", idParameter, deptorParameter);
        }
    
        public virtual int updatedeptor2(Nullable<int> id, Nullable<int> deptor)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var deptorParameter = deptor.HasValue ?
                new ObjectParameter("deptor", deptor) :
                new ObjectParameter("deptor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updatedeptor2", idParameter, deptorParameter);
        }
    
        public virtual int updatedeptor3(Nullable<int> id, Nullable<int> deptor)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var deptorParameter = deptor.HasValue ?
                new ObjectParameter("deptor", deptor) :
                new ObjectParameter("deptor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updatedeptor3", idParameter, deptorParameter);
        }
    
        public virtual int updatedeptor4(Nullable<int> id, Nullable<int> deptor)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var deptorParameter = deptor.HasValue ?
                new ObjectParameter("deptor", deptor) :
                new ObjectParameter("deptor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updatedeptor4", idParameter, deptorParameter);
        }
    
        public virtual int Updatedeptor5(Nullable<int> id, Nullable<int> deptor)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var deptorParameter = deptor.HasValue ?
                new ObjectParameter("deptor", deptor) :
                new ObjectParameter("deptor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Updatedeptor5", idParameter, deptorParameter);
        }
    
        public virtual int Updatedeptor6(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Updatedeptor6", idParameter);
        }
    
        public virtual int UpdateGym1(string name, string manager, string address, string tel, string website, string insta, string telegram, string whatsup, string workhour, string smsusername, string pass, string sender, string weekend, byte[] logo)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var managerParameter = manager != null ?
                new ObjectParameter("manager", manager) :
                new ObjectParameter("manager", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var telParameter = tel != null ?
                new ObjectParameter("tel", tel) :
                new ObjectParameter("tel", typeof(string));
    
            var websiteParameter = website != null ?
                new ObjectParameter("website", website) :
                new ObjectParameter("website", typeof(string));
    
            var instaParameter = insta != null ?
                new ObjectParameter("insta", insta) :
                new ObjectParameter("insta", typeof(string));
    
            var telegramParameter = telegram != null ?
                new ObjectParameter("telegram", telegram) :
                new ObjectParameter("telegram", typeof(string));
    
            var whatsupParameter = whatsup != null ?
                new ObjectParameter("whatsup", whatsup) :
                new ObjectParameter("whatsup", typeof(string));
    
            var workhourParameter = workhour != null ?
                new ObjectParameter("workhour", workhour) :
                new ObjectParameter("workhour", typeof(string));
    
            var smsusernameParameter = smsusername != null ?
                new ObjectParameter("smsusername", smsusername) :
                new ObjectParameter("smsusername", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            var senderParameter = sender != null ?
                new ObjectParameter("sender", sender) :
                new ObjectParameter("sender", typeof(string));
    
            var weekendParameter = weekend != null ?
                new ObjectParameter("weekend", weekend) :
                new ObjectParameter("weekend", typeof(string));
    
            var logoParameter = logo != null ?
                new ObjectParameter("logo", logo) :
                new ObjectParameter("logo", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateGym1", nameParameter, managerParameter, addressParameter, telParameter, websiteParameter, instaParameter, telegramParameter, whatsupParameter, workhourParameter, smsusernameParameter, passParameter, senderParameter, weekendParameter, logoParameter);
        }
    
        public virtual int UpdateGym2(string name, string manager, string address, string tel, string website, string insta, string telegram, string whatsup, string workhour, string smsusername, string pass, string sender, string weekend)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var managerParameter = manager != null ?
                new ObjectParameter("manager", manager) :
                new ObjectParameter("manager", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var telParameter = tel != null ?
                new ObjectParameter("tel", tel) :
                new ObjectParameter("tel", typeof(string));
    
            var websiteParameter = website != null ?
                new ObjectParameter("website", website) :
                new ObjectParameter("website", typeof(string));
    
            var instaParameter = insta != null ?
                new ObjectParameter("insta", insta) :
                new ObjectParameter("insta", typeof(string));
    
            var telegramParameter = telegram != null ?
                new ObjectParameter("telegram", telegram) :
                new ObjectParameter("telegram", typeof(string));
    
            var whatsupParameter = whatsup != null ?
                new ObjectParameter("whatsup", whatsup) :
                new ObjectParameter("whatsup", typeof(string));
    
            var workhourParameter = workhour != null ?
                new ObjectParameter("workhour", workhour) :
                new ObjectParameter("workhour", typeof(string));
    
            var smsusernameParameter = smsusername != null ?
                new ObjectParameter("smsusername", smsusername) :
                new ObjectParameter("smsusername", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("pass", pass) :
                new ObjectParameter("pass", typeof(string));
    
            var senderParameter = sender != null ?
                new ObjectParameter("sender", sender) :
                new ObjectParameter("sender", typeof(string));
    
            var weekendParameter = weekend != null ?
                new ObjectParameter("weekend", weekend) :
                new ObjectParameter("weekend", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateGym2", nameParameter, managerParameter, addressParameter, telParameter, websiteParameter, instaParameter, telegramParameter, whatsupParameter, workhourParameter, smsusernameParameter, passParameter, senderParameter, weekendParameter);
        }
    
        public virtual int UpdateLogin(string username, string name)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateLogin", usernameParameter, nameParameter);
        }
    
        public virtual int UpdatePeople1(Nullable<int> id, string name, string mobile, string address, string mellicode, string type, string type2, byte[] logo)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("mobile", mobile) :
                new ObjectParameter("mobile", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var mellicodeParameter = mellicode != null ?
                new ObjectParameter("mellicode", mellicode) :
                new ObjectParameter("mellicode", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var type2Parameter = type2 != null ?
                new ObjectParameter("type2", type2) :
                new ObjectParameter("type2", typeof(string));
    
            var logoParameter = logo != null ?
                new ObjectParameter("logo", logo) :
                new ObjectParameter("logo", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdatePeople1", idParameter, nameParameter, mobileParameter, addressParameter, mellicodeParameter, typeParameter, type2Parameter, logoParameter);
        }
    
        public virtual int UpdatePeople2(Nullable<int> id, string name, string mobile, string address, string mellicode, string type, string type2)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("mobile", mobile) :
                new ObjectParameter("mobile", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("address", address) :
                new ObjectParameter("address", typeof(string));
    
            var mellicodeParameter = mellicode != null ?
                new ObjectParameter("mellicode", mellicode) :
                new ObjectParameter("mellicode", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var type2Parameter = type2 != null ?
                new ObjectParameter("type2", type2) :
                new ObjectParameter("type2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdatePeople2", idParameter, nameParameter, mobileParameter, addressParameter, mellicodeParameter, typeParameter, type2Parameter);
        }
    }
}
