//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Period
    {
        public int PeriodID { get; set; }
        public string Perioddate { get; set; }
        public string PeriodDesc { get; set; }
        public int peopleID { get; set; }
    
        public virtual People People { get; set; }
    }
}
