//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        public int ProgramID { get; set; }
        public string ProgramName { get; set; }
        public string ProgramTitle { get; set; }
        public byte[] ProgramBinary { get; set; }
        public Nullable<int> PeopleID { get; set; }
    
        public virtual People People { get; set; }
    }
}
