//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_log
    {
        public string PeopleName { get; set; }
        public int LogID { get; set; }
        public int PeopleID { get; set; }
        public string LogDateTimeIN { get; set; }
        public string LogDateTimeOut { get; set; }
        public string PeopleType { get; set; }
        public string PeopleType2 { get; set; }
        public int PeopleDeptor { get; set; }
        public int PeopleCreditor { get; set; }
        public byte[] PeopleLogo { get; set; }
        public System.Guid PicID { get; set; }
    }
}
