//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_newprogram
    {
        public string PeopleName { get; set; }
        public int NewProgramID { get; set; }
        public string NewProgramDate { get; set; }
        public int PeopleID { get; set; }
        public string NewProgramDesc { get; set; }
    }
}
