//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Peyment
    {
        public int PaymentID { get; set; }
        public int PeopleID { get; set; }
        public int PaymentPay { get; set; }
        public string Datetime { get; set; }
        public string PaymentStatus { get; set; }
        public string PaymentSave { get; set; }
        public string PeopleName { get; set; }
    }
}
