//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_shahrieh
    {
        public string ShahriehOUT { get; set; }
        public string PeopleName { get; set; }
        public string PeopleMobile { get; set; }
    }
}
